name: Run homebrew install

on: [push, pull_request]

jobs:
  conftest:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install jcliff
        run: |
          brew tap ${{ github.repository }}
          brew install ${{ github.repository }}/jcliff
