name: Run homebrew install

on: [push, pull_request]

jobs:
  conftest:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Install jcliff
        run: |
          brew tap ${{ github.repository }}
          brew install ${{ github.repository }}/jcliff
