name: Run homebrew install

on: [push, pull_request]

jobs:
  conftest:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

      - name: Install jcliff
        run: |
          brew tap ${{ github.repository }}
          brew install ${{ github.repository }}/jcliff
