name: Run homebrew install

on: [push, pull_request]

jobs:
  conftest:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Install jcliff
        run: |
          brew tap ${{ github.repository }}
          brew install ${{ github.repository }}/jcliff
